###
# sign in request with correct credentials
POST http://localhost:3000/signin
content-type: application/json

{
    "email": "avatar-korra@gmail.com",
    "password": "water"
}

###
# sign in request with incorrect credentials
POST http://localhost:3000/signin
content-type: application/json

{
    "email": "avatar-korra@gmail.com",
    "password": "metal"
}

###
# register new user
POST http://localhost:3000/register
content-type: application/json

{
    "name": "Roku",
    "email": "avatar-roku@gmail.com",
    "password": "fire"
}

###
# register another new user
POST http://localhost:3000/register
content-type: application/json

{
    "name": "Ang",
    "email": "avatar-ang@gmail.com",
    "password": "air"
}

###
# register yet another new user
POST http://localhost:3000/register
content-type: application/json

{
    "name": "Korra",
    "email": "avatar-korra@gmail.com",
    "password": "water"
}

###
# list all users in database
GET http://localhost:3000/

###
# get profile for single user
GET http://localhost:3000/profile/1

###
# add an image entry for a user
PUT http://localhost:3000/findface
content-type: application/json

{
    "email": "avatar-ang@gmail.com"
}